version: '3'

services:
  gogs:
    image: gogs/gogs
    container_name: gogs_local
    ports:
      - "10080:3000" # Accès web via http://localhost:10080
      - "10022:22"   # Accès SSH via le port 10022
    volumes:
      - ./gogs-data:/data # Persistance des données dans un dossier local
    restart: always

  # Optionnel : Interface graphique pour voir les containers (Portainer)
  # si vous voulez gérer ça facilement sans ligne de commande